services:
  foodmerge-db:
    container_name: foodmerge-db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodmerge
      POSTGRES_PASSWORD: Foodmerge2024
      POSTGRES_DB: foodmerge
    volumes:
      - foodmerge-db-data:/bitnami/postgresql
    
volumes:
  foodmerge-db-data:
    
