services:
  foodmerge-db:
    container_name: foodmerge-db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - foodmerge-db-data:/bitnami/postgresql
    
volumes:
  foodmerge-db-data:
    